export type ExtractedRecommendationCandidate = {
  restaurant: string;
  restaurantSlug: string;
  city: string;
  citySlug: string;
  area: string | null;
  address: string | null;
  dishes: string[];
  tags: string[];
  note: string | null;
  snippet: string;
  sourceName: string;
  confidence: number;
  googleMapsUrl: string | null;
  sourceHash: string;
  sourceDate: string;
  rawRefLabel: string;
  threadId?: string;
  sourceMessageIndices?: number[];
  needsCity?: boolean;
};
